### ISSUE TITLE
Custom Reporters Frese Browser

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-vm#245] opened 2016-10-06 22:24 UTC
### Expected behavior

When I drag custom blocks they should place.
### Actual behavior

They freeze my browser and throw these errors:

```
vendor.js.pagespeed.jm.434JizBK7W.js:4 Uncaught TypeError: Cannot read property 

'targetConnection' of nullBlockly.BlockSvg.disconnectInsertionMarker @ 

vendor.js.pagespeed.jm.434JizBK7W.js:4Blockly.BlockSvg.terminateDrag @ 

vendor.js.pagespeed.jm.434JizBK7W.js:4Blockly.terminateDrag_ @ 

vendor.js.pagespeed.jm.434JizBK7W.js:4Blockly.BlockSvg.onMouseUp_ @ 

vendor.js.pagespeed.jm.434JizBK7W.js:4g @ vendor.js.pagespeed.jm.434JizBK7W.js:4

vendor.js.pagespeed.jm.434JizBK7W.js:4 Uncaught TypeError: Cannot read property 'sourceBlock_' of null
```
### Steps to reproduce
1. Go to the Scratch VM ([I used this website to do it](https://utils.asun.co/scratch-vm/playground/))
2. Go to More Blocks
3. Drag the custom reporter on already existing blocks (the one with the report[] included)
4. Look at JS console

or use this XML (oh no! The XML adds custom blocks I did not add )

```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <block type="procedures_defreturn" id="|v5?DM}fOQDHxb]yAWN0" x="132" y="115">
    <field name="NAME">do something</field>
  </block>
  <block type="event_whenflagclicked" id="kO-UNwe9NlxZc@BlO.+u" x="148" y="115"></block>
  <block type="procedures_defreturn" id="xUE}[p?`iSSv;y`TO%G," x="133" y="159">
    <field name="NAME">do something2</field>
  </block>
  <block type="looks_seteffectto" id="`{CFzSvO-Sp8vv%oe0oq" x="148" y="163">
    <value name="EFFECT">
      <shadow type="looks_effectmenu" id="*dVu+)?CMSV-7y@Fx9m,">
        <field name="EFFECT">brightness</field>
      </shadow>
    </value>
    <value name="VALUE">
      <shadow type="math_number" id="h[ERc4qLNz6mmhVGWhNA">
        <field name="NUM">-40</field>
      </shadow>
    </value>
    <next>
      <block type="control_forever" id="Orem,2~_?cdhrNs_V0b+">
        <statement name="SUBSTACK">
          <block type="looks_changeeffectby" id="!E4H6wj)p=s2B1F#:y@a">
            <value name="EFFECT">
              <shadow type="looks_effectmenu" id="U;xfv[sZY8yzS{%0Ceay">
                <field name="EFFECT">color</field>
              </shadow>
            </value>
            <value name="CHANGE">
              <shadow type="math_number" id="q/(B#g(Nkoh`m;ycBpn#">
                <field name="NUM">1</field>
              </shadow>
            </value>
          </block>
        </statement>
      </block>
    </next>
  </block>
  <block type="procedures_callnoreturn" id="`qY9DxfNl0LK);AgMP!/" x="216" y="485">
    <mutation name="do something"></mutation>
  </block>
  <block type="procedures_defnoreturn" id="s(3z`I~G@zezR2-MF!LU" x="117" y="523">
    <field name="NAME">do something</field>
  </block>
</xml>
```
### Operating system and browser

Chromebook (Chrome OS) latest version.

**Comment by mrjacobbloom** [comment] 2016-10-07 06:47
This might be related to LLK/scratch-blocks#610

**Comment by towerofnix** [comment] 2016-10-07 12:22
Yeah, not only is it (seemingly) a duplicate of that, it also has to do with scratch-blocks, not scratch-vm :P

**Comment by CosmicWebServices** [comment] 2016-10-07 13:19
Yeah I think I will keep this open

**Comment by tmickel** [comment] 2016-10-07 17:10
Fixed in scratch-blocks!

**Closed as completed by tmickel** 2016-10-07 17:10 UTC

**Comment by CosmicWebServices** [comment] 2016-10-07 18:40
YAY!
