### ISSUE TITLE
Variable type specifiers ('%s' or '%b') manually entered in custom block title cause issues

### ISSUE THREAD

**Issue by RokCoder** [LLK/scratch-vm#3049] opened 2021-04-24 20:01 UTC
### Expected Behavior

The user should be able to enter any custom block name without issue

### Actual Behavior

Entering %s or %b either at the beginning of a custom name or after a space in a custom name appears to lock up. You can still close the custom block dialog with the 'X' but the blocks listed in the main column are generally collapsed upon one another at that point.

### Steps to Reproduce

Create a new custom block. Call it simply '%s' for the easiest repro.

### Operating System and Browser

Windows 10, Chrome

**Comment by RokCoder** [comment] 2021-04-24 20:02
There are some similarities with https://github.com/LLK/scratch-vm/issues/2577 but I believe this is likely to be a separate issue.

**Comment by apple502j** [comment] 2021-04-24 20:09
Duplicate of LLK/scratch-blocks#2107

**Comment by BryceLTaylor** [comment] 2021-04-29 20:40
Closing as duplicate

**Closed as completed by BryceLTaylor** 2021-04-29 20:40 UTC
