### ISSUE TITLE
Translate block in a say block shows "undefined"

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1328] opened 2018-07-11 20:41 UTC
### Expected Behavior

The translate block should not result in "undefined"

### Actual Behavior

If you put the translate block inside a say block, if the translation result is not cached, the result arrives after the say block runs, so the say bubble says "undefined":

![translate-bug](https://user-images.githubusercontent.com/567844/42598108-32f3a622-8529-11e8-80e7-eb8beeed20df.gif)

Also it's pretty weird that after the block runs, the bubble comes out of the block with the correct translation!

**Comment by thisandagain** [comment] 2018-07-12 20:32
@gnarf @mzgoddard This appears to be a regression caused by #1212. We are going to revert that PR because it is blocking release tomorrow. Would you be open to taking another look here?

**Comment by thisandagain** [comment] 2018-07-12 20:40
![load](https://user-images.githubusercontent.com/747641/42658095-4ff394de-85f2-11e8-8c87-25549cbdd925.gif)

**Comment by thisandagain** [comment] 2018-08-20 13:35
Resolved in https://github.com/LLK/scratch-vm/pull/1335

**Closed as completed** 2018-08-20 13:35 UTC
Labels: bug, critical
