### ISSUE TITLE
Onion skining

### ISSUE THREAD

**Issue by Crispydogs101** [LLK/scratch-vm#3895] opened 2023-02-24 01:01 UTC
Since animating is really popular in scratch. We need to at least a boost up for new animaters since scratch can be for anyone. even people who don't know how to code.

![mockup (2)](https://user-images.githubusercontent.com/114325424/221065765-f0fc4c55-e642-40f2-9e53-2cd2a722ad41.png)
This is a mockup to the feature.
`<span class="sa-onion-button button_button_u6SE2 paint-editor_button-group-button_1I1tm" role="button" data-enabled="false" title="Toggle Onion Skinning"><img class="sa-onion-image paint-editor_button-group-button-icon_10kVn" draggable="false" src="chrome-extension://iliepgjnemckemgnledoipfiilhajdjj/addons/onion-skinning/toggle.svg"></span>
`

- 

`<span class="sa-onion-button button_button_u6SE2 paint-editor_button-group-button_1I1tm" role="button" title="Onion Skinning Settings"><img class="sa-onion-image paint-editor_button-group-button-icon_10kVn" draggable="false" src="chrome-extension://iliepgjnemckemgnledoipfiilhajdjj/addons/onion-skinning/settings.svg"></span>`
This is the code.

**Comment by chrisgarrity** [comment] 2023-02-28 15:36
@Racecar-Roaster thanks for your mockup. Onion skinning is a feature that we have discussed, but it's not a priority right now. Closing this issue as it's a duplicate of the one in [scratch-paint](https://github.com/LLK/scratch-paint/issues/904)

**Closed as not planned** 2023-02-28 15:37 UTC
Labels: feature

**Comment by Crispydogs101** [comment] 2023-02-28 17:00
Alright. Thank you very much for your response.
