### ISSUE TITLE
Single character list export and import bug

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-vm#2155] opened 2019-04-27 02:45 UTC
### Expected Behavior

If a list's all items are single character, export them and import them back will be the same.
![expected](https://user-images.githubusercontent.com/31377746/56843833-00ac6200-68d9-11e9-9db5-1ffe31d1d106.PNG)

### Actual Behavior

I don't want to say anything.
![actually](https://user-images.githubusercontent.com/31377746/56843842-1b7ed680-68d9-11e9-9850-e5604d475e92.PNG)
I don't know if it has to do with the double quote symbol in the list but I must create a special custom block to import them correctly.
Another list that saves the font code is right,
![comparation](https://user-images.githubusercontent.com/31377746/56843866-87f9d580-68d9-11e9-879d-fd2785d545d6.PNG)

### Steps to Reproduce
Create a "single character" list, export and import.
### Operating System and Browser

Win8, Chrome 70

**Comment by griffpatch** [comment] 2019-04-27 07:55
I also have this same problem for double quotes in lists of single
characters.

**Comment by apple502j** [comment] 2019-04-27 11:54
Duplicate of LLK/scratch-gui#4329

**Comment by towerofnix** [comment] 2019-04-27 14:43
This should be fixed by this PR when it is merged: https://github.com/LLK/scratch-gui/pull/4582

**Closed as completed** 2019-04-28 10:26 UTC
