### ISSUE TITLE
Intermittent "Something went wrong" message could offer more detail (Project ID: 339207237)

### ISSUE THREAD

**Issue by RokCoder** [LLK/scratch-vm#2852] opened 2021-02-03 14:11 UTC
### Expected Behavior

Project should load or, at least, exit gracefully

### Actual Behavior

Project usually brings up the "something went wrong" message at least once

![image](https://user-images.githubusercontent.com/20208339/106757449-4195e680-6628-11eb-9e30-65242090cff8.png)

This project contains a LOT of assets so is likely related to that but any loading issue should be trapped and displayed, maybe with a suggestion of closing other tabs or such. It often fails first time on this high-end system which has 64GB RAM, an NVIDIA GeForce RTX 2080 SUPER graphics card, etc. which really shouldn't be having problems with a Scratch project. 

There have been reports of this happening with https://scratch.mit.edu/projects/475832391/ as well though I have only seen this occur myself on rare occasions when loading on a mobile phone.

### Steps to Reproduce

Load the project (https://scratch.mit.edu/projects/339207237/)

### Operating System and Browser

PC Windows 10 Enterprise Version	10.0.18363 Build 18363

**Comment by BryceLTaylor** [comment] 2021-02-04 21:30
Duplicate of https://github.com/LLK/scratch-gui/issues/5844

**Closed as completed by BryceLTaylor** 2021-02-04 21:30 UTC
