### ISSUE TITLE
Uncaught type error: cannot read property "next" or "input" of undefined

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-vm#590] opened 2017-06-05 13:29 UTC
### Expected Behavior

The project should continue to play, regardless of pitch block.

### Actual Behavior

Saskia encountered a bug during the Catch Game Internal playtest (6/2/17):
> Everything stopped working! (I was experimenting with the Pitch block)

Her project froze and was no longer playable.

<img width="431" alt="screen shot 2017-06-05 at 9 17 11 am" src="https://cloud.githubusercontent.com/assets/1320456/26785606/4379eb62-49d1-11e7-810e-4d47200a2991.png">

### Steps to Reproduce

Not sure exactly, but a good starting place might be to use the pitch blocks, maybe starting with the configuration shown in this screenshot (https://github.com/LLK/scratch-render/issues/78#issuecomment-306185191) that Jie took (Jie seemed to have ran into multiple bugs around the time of the screenshot).

### Operating System and Browser

_Chrome & Mac OS_

**Comment by paulkaplan** [comment] 2017-06-07 12:03
I _believe_ this has the same root cause as https://github.com/LLK/scratch-vm/issues/589 : the vm block list gets out of sync with what is on the workspace because of block ID collisions. 

@rschamp we could make these VM functions resilient to missing blocks by doing more asserting when we look up blocks, but I would rather know the root cause (which I believe is https://github.com/LLK/scratch-blocks/issues/926). I worry about fixing it in the VM because it will (a) cover up bugs and (b) lead to some undefined behavior, breaking something further down the line (e.g. in this case it might lead to blocks mysteriously disappearing when switching tabs). So I think our best course right now is to fix the root cause of ID collisions.

**Comment by paulkaplan** [comment] 2017-06-09 21:39
Fixed by https://github.com/LLK/scratch-blocks/pull/936, but we'll keep an eye out for any such issues during the playtest monday

**Closed as completed by paulkaplan** 2017-06-09 21:39 UTC
Labels: has-patch
