### ISSUE TITLE
Set volume in a loop causes crunchy/clicky static

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-vm#2261] opened 2019-08-15 13:21 UTC
### Expected Behavior

_Please describe what should happen_
Set volume should smoothly adjust the currently playing sounds volume.

### Actual Behavior

_Describe what actually happens_
Using a stack like this, I get lots of static/crunchiness 
![image](https://user-images.githubusercontent.com/654102/63097203-d5a85580-bf3d-11e9-9abf-ccc9d89ad480.png)

### Steps to Reproduce
[Set Volume Bug (1).sb3.zip](https://github.com/LLK/scratch-vm/files/3505622/Set.Volume.Bug.1.sb3.zip)

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

Mac/Chrome

/cc @ericrosenbaum I didn't see any bugs filed related to the set volume issues. I'm not sure if this is what you meant about the "wierdness" but this is at least one aspect that is bad.

**Comment by ericrosenbaum** [comment] 2019-08-15 13:32
Thanks @paulkaplan! possibly a duplicate of https://github.com/LLK/scratch-audio/issues/111

Lets find a time to look together at https://github.com/LLK/scratch-audio/pull/118/files, which may be part (or all?) or the fix for this and other related issues

**Closed as completed** 2019-08-15 15:25 UTC
Labels: bug
