### ISSUE TITLE
Renaming a costume, sound or sprite stops blocks using those names from working 

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-vm#912] opened 2018-01-22 17:44 UTC
### Expected Behavior

_Please describe what should happen_

If you have a "forever => play sound 'meow'", and then rename the "meow" sound in the sound editor, the loop stops playing sounds. Same for costume blocks and the "touching <sprite name>" blocks. 

These updates should update the blocks that are referring to them.

**Comment by kchadha** [comment] 2018-01-23 16:03
Looking into this, I found that the dropdown menu options correctly update, but the currently selected field option does not. One remedy for this would be to update the xml of any block that could refer to a costume, sound, or sprite name every time one of these changes. This does not seem like a good option to me because there is no set list of all the blocks that would be affected by these changes (at least I am not aware of such a list). How would we know definitively that we are updating all the fields of all the blocks that could refer to any of these things (sprite name, costume name, sound name, clone name, backdrop name)?

I think a better fix for this would be to handle this dynamically in scratch-blocks. The following proposed solution might be over-kill, so it definitely needs discussion.

Right now, the dropdown menus for any block fields that refers to these things are handled by the following functions in `scratch-gui/src/lib/blocks.js`: 

[`soundsMenu`](https://github.com/LLK/scratch-gui/blob/develop/src/lib/blocks.js#L31), `costumesMenu`, `backdropsMenu`, `spriteMenu`, `cloneMenu`. 

These functions are called by the init functions for each of the dropdowns that should use these specialized functions.

Each of these functions populates the dropdown menu options with a list of text-value pairs. The text is the user-readable text displayed in the dropdown, and the value is the underlying value of that option. 

Right now, both the text and the value are the same thing. In variable dropdowns however, we are now doing something smarter, where the text is the name of the variable, but the value is the unique identifier for the variable, allowing us to look up the selected option by value and keep it up to date in scratch-blocks. I propose we do something similar here for each of these dropdown menus that are populated with sprite names, costume names, sound names, etc.

Thus, even if the name of a sprite changes, we can ensure that the name of the selected field option gets updated by looking up the Id.

**Comment by kchadha** [comment] 2018-01-23 19:07
@rachel-fenichel Since this discussion possibly affects scratch-blocks, do you have any thoughts about this?

**Comment by rachel-fenichel** [comment] 2018-01-26 21:57
This decision sounds good to me.

Per discussion with @kchadha this only works because it's not currently possible to edit one of these names while it's being displayed on a block.
If that ever happens we'll need to do something more aggressive to make sure the name is updated on all blocks on the rendered workspace.

**Comment by paulkaplan** [comment] 2018-01-29 13:40
> Per discussion with @kchadha this only works because it's not currently possible to edit one of these names while it's being displayed on a block.

What about the "touching <sprite name>" block, which can be edited through the sprite name field on the right while the blocks tab is visible.

**Comment by kchadha** [comment] 2018-01-29 14:37
Correct me if I'm wrong because I haven't thought long and hard about this, but it just so happens to be that the "touching" block refers to all sprite *other* than the one that is currently selected. To edit the name of any sprite this block can refer to, you would have to switch to one of those other sprites (so the block stops being visible in the workspace, because the workspace switches to that other sprites blocks). 

This discussion would be moot if there was another way to rename a sprite without having to select it first (e.g. right-clicking on the sprite icon, and having a rename option in its context menu).

**Comment by paulkaplan** [comment] 2018-01-29 14:44
aha! good point :)

I'm concerned about the amount of work it would take to move all of the menus to an ID system. Do you have a solid idea of that? 

Also @thisandagain i think we should promote this to a critical issue, because it is currently stopping any renaming from functioning on costumes/sounds/sprites when there are existing blocks.

**Comment by kchadha** [comment] 2018-02-02 14:30
After talking with @paulkaplan, we decided that it's best to update the XML to reflect the renames for each block on any of the sprites workspaces that reference the sprite/sound/costume name.
Going with the unique id solution described above would break the following functionality:

1. use a `play sound [Meow v] until done` block on the workspace
2. delete the sound 'Meow' from the sound editor
3. Add a new sound and name it 'Meow' and have the original block still work.

Maintaining this behavior is very important from a UX perspective.

Attempting this fix yesterday, I discovered that resolving this issue seems to be blocked because of the regression discussed in #924. @cwillisf and I are working to figure out what's going on with that one.

**Closed as completed** 2018-02-12 16:53 UTC
Labels: feature, has-patch, needs-discussion
