### ISSUE TITLE
EV3 motor block causes distance to return 0

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-vm#1363] opened 2018-07-17 21:41 UTC
### Expected Behavior

The distance block should not be related to the motor block.

### Actual Behavior

When you run the rotate motor block the distance briefly becomes 0.  This will trigger the `distance < ` block and affects the reporter.

### Steps to Reproduce

Add the EV3 Extension and connect an EV3
Connect a motor and a distance sensor to the EV3 hub
Build a stack that says Forever Say Distance
Run the stack
Click the rotate motor block
Note: the distance drops to 0 briefly

### Operating System and Browser

Edge on Windows and Chrome on Mac

**Comment by thisandagain** [comment] 2018-07-19 12:43
This causes a lot of confusion if you have the "when distance < [n]" hat block and a motor block in the same project.

**Comment by evhan55** [comment] 2018-08-17 16:21
Could no longer reproduce, so closing because it might be resolved.

**Closed as completed by evhan55** 2018-08-17 16:21 UTC
Labels: bug, extensions, critical
