### ISSUE TITLE
In Say, decimal shows where param is number (not string)

### ISSUE THREAD

**Issue by maxiostro** [LLK/scratch-vm#971] opened 2018-03-08 20:34 UTC
Simple, when I use Say(text) it works. With Say(1) it works too. But when the input is a real number, not a number to string, it adds two decimal to the number.s

**Comment by towerofnix** [comment] 2018-03-09 00:56
This is a duplicate of #960, which has a PR fixing it (#965).

**Comment by thisandagain** [comment] 2018-03-26 19:39
Resolved in https://github.com/LLK/scratch-vm/pull/965

**Comment by thisandagain** [comment] 2018-03-26 19:39
(Thanks @towerofnix !)

**Closed as completed by thisandagain** 2018-03-26 19:39 UTC
