### ISSUE TITLE
Edge-triggered hat blocks don't run their entire stack

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-vm#610] opened 2017-06-15 15:55 UTC
### Expected Behavior

Hat block should execute the entire thread associated with it when triggered, not just the first block under it.

### Actual Behavior

The hat block runs the 1st block in its stack, but not the others.

Note: noticed with @ericrosenbaum on his github page showing his extension fork.

### Steps to Reproduce

- Use the WeDo 2.0
- When distance < 50 block
- Drag out two of the drum blocks
- Set them to two different drum sounds
- Trigger the stack with the distance sensor
- Note only the first drum sound plays

**Examples:**
<img width="342" alt="screen shot 2017-06-15 at 11 53 22 am" src="https://user-images.githubusercontent.com/1320456/27190161-939e0b80-51c1-11e7-9df3-11ff4f94cfa2.png">
<img width="1280" alt="screen shot 2017-06-15 at 11 50 34 am" src="https://user-images.githubusercontent.com/1320456/27190162-939e36f0-51c1-11e7-8a53-0df9a6fcd362.png">

### Operating System and Browser

_Mac, Chrome 59_

**Comment by jwzimmer-zz** [comment] 2017-06-16 20:37
@morantsur also reported (something that sounds like) this during the Extensions Internal Playtest (6/16/17):
> only the first speak block was activated (out of three)

**Comment by ericrosenbaum** [comment] 2017-06-16 21:03
This bug does not actually seem to be related to the restartExistingThreads being true (I've now set all of the extension hats to have restartExistingThreads false). It does seem to be specific to hats with edgeActivated set to true.  I thought it might have something to do with having two copies of the same hat running, but I can't reproduce it just by trying that.

**Comment by carljbowman** [comment] 2017-06-22 14:55
This is a dupe of https://github.com/LLK/scratch-vm/issues/153

**Closed as completed by carljbowman** 2017-06-22 14:56 UTC
Labels: bug
