### ISSUE TITLE
Import of "1.0" is converted to "1"

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-vm#376] opened 2017-01-12 10:24 UTC
### Expected behavior

When importing an existing project, a numeric value of "1.0" should be imported as "1.0".

### Actual behavior

Currently numeric values do not keep their decimal places on import. This prevents the random number generator from calculating floating point numbers when the range is set to -1.0 to 1.0 as the 0's are stripped off.

### Steps to reproduce

Import this project '138856666'. See how the pick random -5.0 to 5.0 is imported as -5 to 5.

### Operating system and browser

PC chrome.

**Comment by CosmicWebServices** [comment] 2017-01-12 11:39
I think this was a problem for me in scratch 2 actually.

**Comment by griffpatch** [comment] 2017-01-27 10:47
This is not actually a Scratch 3 issue as it is also present in Scratch 2 it appears. See this log:

https://github.com/LLK/scratch-flash/issues/1270

**Comment by SillyInventor** [comment] 2017-01-30 16:54
The problem is with the saved script, as the save doesn't include the .0:

![screenshot from 2017-01-30 11-43-58](https://cloud.githubusercontent.com/assets/8440451/22432164/fcc4dd64-e6e1-11e6-8116-f1234d0bf648.png)

The Scratch 3.0 export seems to have this functionality. Try to export to xml with .0, then import, the script will have the needed number of decimals.

![image](https://cloud.githubusercontent.com/assets/8440451/22432338/9302f522-e6e2-11e6-8b31-11e2ae0a1727.png)

**Comment by thisandagain** [comment] 2017-01-30 16:59
Thanks @griffpatch and @SillyInventor. I'm going to close this and track in 2.0:
https://github.com/LLK/scratch-flash/issues/1270

**Closed as completed by thisandagain** 2017-01-30 16:59 UTC
Labels: bug, help wanted
