### ISSUE TITLE
project.json with certain modifications can cause Scratch to break

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-vm#2332] opened 2020-03-12 17:18 UTC
### Expected Behavior
project.json should not break Scratch, for example make Scratch not respond, or fail to load default projects after that. Because uid generator only generates uid with length 20, those cannot happen without project.json modifying, but this should be either invalidated by parser or correctly handled.

### Actual Behavior
Behavior A: Infinite loop and error inside `execute.js` saying oop is undefned
Behavior B: Projects fail to load, but the default project won't load correctly

### Steps to Reproduce
Behavior A can be seen if you modify the project.json `variables` section like this:
```
            "variables": {
                "toString": [
                    "変数",
                    0
                ]
```
and then opening the project and clicking show variable block.

Behavior B can be seen if you modify the `blocks` section like above, but with `hasOwnProperty`. Projects fail to load, but the default projects won't load afterwards. This may have something with GUI reducer [not handling LOADING_VM_FILE_UPLOAD](https://github.com/LLK/scratch-gui/blob/develop/src/reducers/project-state.js#L325).

### How to Fix
Simple thing: invalidate those keys.
Complex thing 1: Re-assign uids to those.
Complex thing 2: Change all calls to those objects' properties with safer ones. For example, `hasOwnProperty` can be replaced with `in` operator.

### Operating System and Browser
Windows 10, Firefox 74

**Comment by BryceLTaylor** [comment] 2020-03-17 14:47
@apple502j Can you please add reproduction steps including how you load the project in this situation?  Is it possible to end up saving such a project onto the server?

**Comment by adroitwhiz** [comment] 2020-03-17 14:57
1. Create a new project
2. Download it via File > Save to your computer
3. Open the `.sb3` file as a `.zip` (you may need to rename it)
4. Open the `project.json` file inside of it
4a. The start of it should look something like
   ```
   {"targets":[{"isStage":true,"name":"Stage","variables":{"`jEk@4|i[#Fk?(8x)AV.-my variable":["my variable",0]}
   ```
5. Replace the variable ID (the string of random characters followed by `-my variable` with `"toString"`, like so:
5a.
    ```
   {"targets":[{"isStage":true,"name":"Stage","variables":{"toString":["my variable",0]},
   ```
6. Save the `project.json` file and ensure the .zip/.sb3 includes the updated version
7. If you had to change the file extension to .zip, change it back to .sb3
8. Upload the modified .sb3 file via File > Load from your computer
9. If you click ![image](https://user-images.githubusercontent.com/25993062/76868885-e7d4d400-683d-11ea-8fc3-dd76cafd9bb9.png), it will never finish executing
10. You can save the project, but when you reload it, it will show the "Oops!" screen

**Comment by BryceLTaylor** [comment] 2020-03-17 15:43
Since this only affects the edited project json and a user can't get into the state without editing it, I'm closing this issue.

**Closed as completed by BryceLTaylor** 2020-03-17 15:43 UTC
