### ISSUE TITLE
Error Saving Project With `\b`

### ISSUE THREAD

**Issue by AmazingMech2418** [LLK/scratch-vm#3749] opened 2022-09-21 20:50 UTC
### Expected Behavior

All projects should be able to save.

### Actual Behavior

If a project has `\b` as an input or value stored in a variable, the project won't save, a downloaded copy will fail to load, and an error will show in the console when attempting either of these.

### Steps to Reproduce

Create a project with `\b` in a variable or input for any block and try to save it.

This should be able to be fixed with a minor update to serialization that escapes `\b`. It seems the JSON.parse function automatically encodes the sequence into a backspace, which results in the error.

**Comment by cwillisf** [comment] 2022-09-22 14:21
Thanks for the quality report! I'm curious: how did you find this? :D

**Comment by mxmou** [comment] 2022-09-22 16:11
Looks like a duplicate of LLK/scratch-parser#56 (loading) and LLK/scratch-www#3497 (saving).

**Comment by AmazingMech2418** [comment] 2022-10-17 19:14
> Thanks for the quality report! I'm curious: how did you find this? :D

Thank you! I was actually working on a lambda calculus implementation in Scratch, using "`\`" as the lambda symbol (since the actual lambda isn't on most keyboards), and having a parameter of b led to part of the code being `\b.<stuff here>`, and I then noticed it wouldn't save, so I looked through the error messages and figured out what the issue was.

**Closed as completed** 2022-12-13 19:33 UTC
Labels: priority 4, Low Impact, High Severity
