### ISSUE TITLE
Clicking on arithmetic expression yields different result to watcher

### ISSUE THREAD

**Issue by RokCoder** [LLK/scratch-vm#2696] opened 2020-11-17 09:46 UTC
### Expected Behavior

Clicking on arithmetic expression or variable should display same result as watcher

### Actual Behavior

![image](https://user-images.githubusercontent.com/20208339/99398363-3a3e2700-28dc-11eb-9b52-967e563bc557.png)

![image](https://user-images.githubusercontent.com/20208339/99398421-4cb86080-28dc-11eb-86c5-00646ffb17c6.png)

### Steps to Reproduce

Enter expression as above and click on it. Assign expression to variable and click on it. Compare to watcher value displayed.

### Operating System and Browser

Mac OS 11.0.1 Chrome 6.0.4240.198

**Comment by RokCoder** [comment] 2020-11-17 09:47
Possibly related to https://github.com/LLK/scratch-vm/issues/1484 ?

**Comment by adroitwhiz** [comment] 2020-11-17 09:48
See also https://github.com/LLK/scratch-vm/issues/2342

**Comment by BryceLTaylor** [comment] 2021-05-03 21:01
This is not exactly the same as #2342 but it has the same root cause and would be addressed at the same time.  I'm closing this one as a duplicate.

**Closed as completed by BryceLTaylor** 2021-05-03 21:01 UTC
