### ISSUE TITLE
Edge triggered hats can trigger continuously after duplication

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-vm#1507] opened 2018-08-20 21:12 UTC
### Expected Behavior

An edge-triggered hat (such as "when tilted left") should trigger a stack to run once, at the moment the tilt value crosses the threshold in that axis.

### Actual Behavior

If you duplicate a sprite with an edge triggered hat, then change the input on the duplicated hat, both hats will now trigger 30 times per second, instead of once.

In the gif below, at first with just one sprite, it has the correct behavior: each button press causes the sprite to turn 15 degrees. After duplicating and switching the second sprite's hat to "when B button pressed," now each sprite turns continuously when you press its button. 

![hat-duplicate-bug](https://user-images.githubusercontent.com/567844/48443466-38768180-e75f-11e8-8454-1c99ebdaf0b6.gif)

### Steps to Reproduce

- Add the microbit extension
- Build the stack `when A button pressed / turn 15 degrees`
- Note that pressing the button causes the sprite to turn 15 degrees, running the stack once
- Duplicate the sprite
- In the duplicate, change the input on the hat to B
-  Note that pressing either button causes the corresponding sprite to turn continuously

**Comment by BryceLTaylor** [comment] 2018-10-31 14:36
I'm unable to reproduce this.  I'll close it for now and keep my eye out for regressions.

**Comment by ericrosenbaum** [comment] 2018-11-11 20:16
I was just able to repro this, finally. It happens when you have an edge-triggered hat in a sprite, then duplicate the sprite, then change the input on the edge-triggered hat in the duplicate (e.g. from "when tilted left" to "when tilted right"). Now, when either hat has a true condition, it triggers continuously (i.e. the stack is started 30 times per second, rather than the expected single time).

Because it's caused by duplication, I would guess it is closely related to https://github.com/LLK/scratch-vm/issues/1495

**Closed as completed** 2018-12-13 02:13 UTC
Labels: bug, has patch
