### ISSUE TITLE
Altering sound effects (volume, pitch, etc) yields within non-refresh custom block

### ISSUE THREAD

**Issue by RokCoder** [LLK/scratch-vm#3008] opened 2021-04-01 15:51 UTC
### Expected Behavior

A custom block should never yield (other than when completing or timing out). I should be able to alter volume and pitch within a non-refresh block without incurring extra frames running. Because of this incorrect behaviour, complex sound effects cannot be implemented at present.

### Actual Behavior

Making a non-refresh custom block with multiple sound-altering blocks in it results in execution spanning multiple frames.

### Steps to Reproduce

Simply animate and perform sound alterations in a non-refresh block. The sample project does exactly this -
https://scratch.mit.edu/projects/510323931/

### Operating System and Browser

Windows 10

**Comment by apple502j** [comment] 2021-04-01 16:52
Duplicate of #2079

**Comment by BryceLTaylor** [comment] 2021-04-01 20:29
Closing as duplicate

**Closed as completed by BryceLTaylor** 2021-04-01 20:29 UTC
