### ISSUE TITLE
When use the LEGO BOOST extension , error command for the motor-A 

### ISSUE THREAD

**Issue by wangpengli** [LLK/scratch-vm#2233] opened 2019-07-14 02:02 UTC
### Expected Behavior

I use block which have a command for the motor-A , the motor-A should turn 5s.

### Actual Behavior

no any happend.

### Steps to Reproduce

I chaned the param to motor-D, the extern-motor turned.

### Operating System and Browser

windows 10.

**Comment by wangpengli** [comment] 2019-07-14 02:03
when the moto-D turned , I checked the model, the extern-motor plug in the port C

**Comment by apple502j** [comment] 2019-07-14 03:57
Duplicate of #2215

**Comment by wangpengli** [comment] 2019-07-14 09:45
yes, got it , I check the same code in another boost , which not update with the boost app, the motor block have no problem. thank you .

**Closed as completed** 2019-08-02 13:41 UTC
